# Generated by Django 4.2.13 on 2024-05-08 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GreenHous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hight', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Standart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('idCondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websev.condition')),
                ('idGreenHouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websev.greenhous')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('idGreenHous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websev.greenhous')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('idGreenHouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websev.greenhous')),
            ],
        ),
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.CharField(default='08.05.2024', max_length=10)),
                ('idCondition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websev.condition')),
                ('idSensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websev.sensor')),
            ],
        ),
    ]
