# Generated by Django 4.2.13 on 2024-05-09 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websev', '0003_rename_greenhous_greenhouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate',
            name='date',
            field=models.CharField(default='09.05.2024', max_length=10),
        ),
        migrations.AlterField(
            model_name='climate',
            name='time',
            field=models.TimeField(default=datetime.time(3, 56, 15, 209065)),
        ),
    ]
