# Generated by Django 4.2.13 on 2024-05-10 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websev', '0005_greenhouse_name_alter_climate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate',
            name='date',
            field=models.CharField(default='10.05.2024', max_length=10),
        ),
        migrations.AlterField(
            model_name='climate',
            name='time',
            field=models.TimeField(default=datetime.time(18, 44, 34, 303114)),
        ),
    ]
