# Generated by Django 4.2.13 on 2024-05-13 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websev', '0007_alter_climate_date_alter_climate_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='idGreenHouse',
        ),
        migrations.RemoveField(
            model_name='standart',
            name='idCondition',
        ),
        migrations.RemoveField(
            model_name='standart',
            name='idGreenHouse',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='idCondition',
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='description',
            field=models.CharField(default='Описания нет', max_length=255),
        ),
        migrations.AddField(
            model_name='sensor',
            name='standart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='climate',
            name='date',
            field=models.CharField(default='13.05.2024', max_length=10),
        ),
        migrations.AlterField(
            model_name='climate',
            name='time',
            field=models.TimeField(default=datetime.time(16, 34, 39, 371631)),
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.DeleteModel(
            name='Standart',
        ),
    ]
