# Generated by Django 5.0.6 on 2024-05-14 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websev', '0009_alter_climate_date_alter_climate_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climate',
            name='date',
        ),
        migrations.AlterField(
            model_name='climate',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
